### ISSUE TITLE
Add option to control show_cb argument in precrec objects

### ISSUE THREAD

**Issue by henrifnk** [mlr-org/mlr3viz#55]
Is it an option to control `show_cb` to the autoplot function for `precrec` objects by parsing the argument through the ellipsis?

**Comment by jakob-r** [comment]
I checked and it does not make much sense to pass the arguments to `precrec::autoplot()` since most arguments depend on how we execute `precrec::evalmod()`. So there would be more logic necessary.

However, I found out that we already used `show_cb` but in the wrong place, so it did not have any effect. So maybe it is enough to just show the confidence bounds if they are available?

**Comment by mllg** [comment]
`show_cb` can now be passed down. If it is not applicable, it will automatically be set to `FALSE`.
